### PR TITLE
update definitions au & nz and add ee.yaml .

### PR DESCRIPTION
**Pull request by ttwo32**
see detail https://github.com/holidays/definitions/pull/43.

### CODE REVIEW

**Comment by ttwo32** [comment]
Hi @ppeble . 
I cannot merge this by myself.
Please review this when you have a time. :)

**Comment by ppeble** [comment]
Bah! I don't understand, you should have write access. This is _still_ not fixed! I'll look into it today. 😬

**Comment by ppeble** [comment]
@ttwo32 I think I FINALLY figured out why you couldn't merge. Sorry! Let's see how it goes next time. 👍

**Comment by ttwo32** [comment]
@ppeble Thank you for merging this!! I will check at next time..:smile:

**Pull request merged**
