### PR TITLE
adds holidays for Malaysia

### PR DESCRIPTION
**Pull request by sas1ni69**

### CODE REVIEW

**Comment by ptrimble** [comment]
Thank you for the submission! I will take a look by the end of the weekend and let you know if I have any questions.

**Comment by sas1ni69** [comment]
No worries, take your time. Thanks Phil 💃

**Comment by ptrimble** [comment]
Thanks for waiting! The definitions themselves look great but I don't see the generated tests included. Could you push those up? Once you do I'll go ahead and merge. 👍 

Thanks!

**Comment by sas1ni69** [comment]
Hey Phil, sure I'll include those today. Thanks again!

**Comment by ptrimble** [comment]
Heya @sas1ni69, do you think you'll be able to rebase and push the test files? Sorry for the rebase requirement, I didn't realize that my last merge would impact you. 😢

**Comment by sas1ni69** [comment]
Hey @ptrimble no worries at all, I appreciate you updating me :) I've gone ahead and updated the PR and rebased. Thanks!

**Comment by ptrimble** [comment]
Looks great! I'll get this out as a minor point version release in the next few days. 👍 

Thanks so much for the PR!

**Comment by sas1ni69** [comment]
Thanks so much :) I'd be happy to help out on issues or new features out in my spare time if you'd like the help. Let me know.

**Comment by ttwo32** [comment]
@sas1ni69 Thank you so much!! Good PR. 👍

**Comment by sas1ni69** [comment]
@ttwo32 you're most welcome!

**Pull request merged**
