### PR TITLE
Bulgarian Holidays (latin and cyrillic)

### PR DESCRIPTION
**Pull request by thekazak**
Bulgarian Holidays (latin and cyrillic)
when_easter gem is used to calculate Easter as per Julian calendar

### CODE REVIEW

**Comment by ptrimble** [comment]
Thanks for this! Do we really need to add another gem, though? Does the existing `orthodox_easter` function not cover what we need?

Take a look, let me know if it won't work instead: https://github.com/alexdunae/holidays/blob/master/lib/holidays.rb#L250-L272

**Comment by thekazak** [comment]
it seems the formula implemented here https://github.com/alexdunae/holidays/blob/master/lib/holidays.rb#L250-L272 calculates Easter as per Gregorian calendar only. There is a difference between orthodox Easter calculated as per Gregorian and Julian calendar. In Bulgaria we celebrate Easter as per Julian calendar. That's why we decided to use when_easter gem as a quicker solution, as Julian calendar is already implemented there, but of course it could be done the same way inside holidays gem  with relevant changes in implemented formula for Gregorian calendar.
You can check differences between Gregorian and Julian calendar regarding orthodox Easter calculations here
http://www.ortelius.de/kalender/east_en.php

**Comment by ptrimble** [comment]
Hm...gotcha. Sorry for the delay. Let me take a deeper look at this.

Bug me if I lose track of this. :smile:

**Comment by thekazak** [comment]
Hi,
any news on this ? :)

**Comment by ptrimble** [comment]
I apologize, I completely lost track of this, even after making a point to NOT do it. I am trying to clean up a few other refactor points and will look at this in light of those changes. Sorry again, I'll do my best to make a decision on how to proceed in the coming week.

**Comment by ptrimble** [comment]
Thank you for your INCREDIBLE patience with this. I am looking at it right now, it's my top priority now that the refactor is merged.

**Comment by ptrimble** [comment]
In case anyone cares, I am also adding this to the 'Europe' defs. As a filthy American I don't know if this is good or bad. I can remove it if I am drastically wrong. :smile:

**Comment by ptrimble** [comment]
After all this time I'm gonna be a jerk and wait to hear back from the author of `when_easter`. I would prefer to pull the Julian easter calculation from the other gem and add it to `holidays` rather than add a runtime dependencies considering we have no other runtime dependencies currently. If he is okay with it I'll personally make the change and merge.

If I don't hear back in a reasonable amount of time (a few days) then I'll just do it and provide proper attribution. We'll see how it goes.

Thanks again for your patience, I know I've been a real jerk in letting this drag on for so long. No excuses here! Just happy to almost be through all of my open PRs. :smile:

**Comment by ptrimble** [comment]
Quick update, I heard back and have the green light to pull the julian calendar calculation into this gem. I will do it after work today.

**Comment by ptrimble** [comment]
Closing this and moving to https://github.com/holidays/holidays/pull/150

**Pull request closed without merging**
