### PR TITLE
German city specfic holiday

### PR DESCRIPTION
**Pull request by fschaeffler**
There's a public holiday in Augsburg, Bavaria (BY), Germany. It is every year on the 8th of August. Unfortunately,  there's only a German Wikipedia article, which can be found here http://de.wikipedia.org/wiki/Augsburger_Hohes_Friedensfest .

For the implementation, I did the following:
- added the holiday in data/de.yaml
- added tests for getting / not getting this day as a public holiday depending on the specified region
- added a new region in lib/holidays/de.rb

### CODE REVIEW

**Comment by ptrimble** [comment]
Thanks @fschaeffler! I think that this looks great. I just have two minor questions:

* Could you please run `rake generate` as specified in the 'How to Contribute' section of the README to generate the actual ruby files that are included at runtime and push that up to your branch?
* Could you help me understand the 'aux' designation? Is there an ISO code for Augsburg that I cannot find? I understand the ':de_by' to be for Bavaria but I can't seem to find anything for Augsburg.

Thanks again, these are minor things. Once we get them resolved I'll go ahead and merge.

**Comment by fschaeffler** [comment]
AUX is not an ISO-code, as I couldn't find any ISO-codes for cities. However, AUX is the IATA-code for Augsburg.

**Comment by ptrimble** [comment]
Hm, I'm worried because I don't see the update in de.rb that has the new 8/8 holiday. Let me monkey with this a bit to try to diagnose the problem.

**Comment by ptrimble** [comment]
Oh, and the IATA-code is good enough for me! Thanks for explaining.

**Comment by ptrimble** [comment]
I'm not sure what is going on with the generate so I just took your changes and did it on my own branch (using your name for the commit). I'll close this PR and we can use the other one: https://github.com/holidays/holidays/pull/143

**Pull request closed without merging**
