### PR TITLE
update generated definitions

### PR DESCRIPTION
**Pull request by Garllon**
I updated the generated definitions, because i need some specific holidays, like 'Tag der Befreiung (08.05.2020)', which was not in included currently. I am a little bit confused that there are changes in the definitions repo master, but the version was not bumped up. So maybe first we should publish a new version in the definitions project. 

I also persisted the bundler version to 2.0.2, because of the known issue: [Bundler 2.1.0 does not expose executables from gems without "bundle exec"](https://github.com/bundler/bundler/issues/7494)

### CODE REVIEW

**Comment by estani** [comment]
The definitions where updated 3 months ago and there's a release of it v5.0.1, but the v8.0.0 is pointing to an older version... I think either the 5.0.1 Tag got moved, or some state was used in v8.0.0 before the v5.0.1 was released. In either case, the v5.0.1 of definitions is from december and the v8.0.0 from September.

@ppeble  This change need to be merged, I'd go with 8.0.1 since is a definitions only change, no code. But that's just me. We also need this, so it would be much appreciated if it get merged. Thanks.

**Comment by Garllon** [comment]
Hi @ttwo32, thanks for the update. Your right, they fixed it, so i removed the restriction. :)

**Comment by ttwo32** [comment]
@Garllon 
Thank you!!
I would merge this PR.
Just a moment,please. :)

**Comment by ttwo32** [comment]
Merged.

**Comment by ttwo32** [comment]
Bump up version to [8.1.0](https://rubygems.org/gems/holidays).
Please checkout!! :)

**Pull request merged**
