### PR TITLE
Use case refactoring

### PR DESCRIPTION
**Pull request by ptrimble**
This PR accomplishes the following:

* move factories into their own namespace for clarity
* completely kill the concept of `use_cases` and move them all under `finder` where they belong
* kill `options` and just put it under `finder` since that is the only place it is used

### CODE REVIEW

**Comment by ptrimble** [comment]
Uuuugghhhh one of the gems required by coveralls made a breaking change, I guess, without a major version bump. And now we are failing in jruby.

I'll try to figure out what is going on this weekend.

**Comment by ptrimble** [comment]
Seems like tins made a breaking change. I rolled back to a working `coveralls` change and opened issues against both projects. I should be good to go with this PR.

**Comment by ttwo32** [comment]
@ptrimble 👍 
I agree with your thoughts.
I have founded caverall's commit(https://github.com/lemurheavy/coveralls-ruby/commit/ef89fac8a07c951f8f999bbb085f4727e8b5149d)  too.
Tins's version was changed.
I have tried to install tins gem in jruby 1.7.* and latest jruby too,
and jruby 1.7.* occured tins's intall error.(see below)

`MacBook-Pro:jrubytest xxxx$ rbenv local`
`jruby-1.7.19`
`MacBook-Pro:jrubytest xxxx$ gem install tins`
`ERROR:  Error installing tins:`
	`tins requires Ruby version >= 2.0.`

**Comment by ptrimble** [comment]
There we go. I think it was just an update issue. 😄

**Comment by ptrimble** [comment]
I'm going to go ahead and merge this and continue with other refactoring.

As a side note, I opened issues on [tins](https://github.com/flori/tins/issues/14) and [coveralls](https://github.com/lemurheavy/coveralls-ruby/issues/104) to ask them to begin using semver. 

Their dropping of jruby 1.7.x support (basically, requiring ruby 2+) is a reasonable change and, to be honest, I didn't know that jruby 1.7 was *not* ruby 2+ compatible. We have already dropped ruby 1.9 support and probably should drop jruby 1.7 support in our next major version bump. The issue I have is that they should not drop support for an entire version of ruby without a major version bump. 

I have opened an issue to drop jruby 1.7 support in a future major version bump so I don't lose track of it.

**Pull request merged**
