### PR TITLE
Add support for Luxembourg

### PR DESCRIPTION
**Pull request by dunyakirkali**

### CODE REVIEW

**Comment by ttwo32** [comment]
Good PR. 👍

**Comment by dunyakirkali** [comment]
Is it already known when the next release will happen?

**Comment by ptrimble** [comment]
It can happen at any time. I'm getting over some kind of sinus thing but once I am back up on my feet I'll take a look at this, merge it, and get a new version out. Thanks for your patience.

**Comment by ptrimble** [comment]
Great! I'll merge and get it out tonight. Thanks your contribution!

**Pull request merged**
