### PR TITLE
Definitions for Republic of Korea (South Korea)

### PR DESCRIPTION
**Pull request by jonathanpike**
I added definitions for the Republic of Korea, including those holidays based on the Lunar calendar (from 1901 - 2050).  Hope this is helpful!

### CODE REVIEW

**Comment by ptrimble** [comment]
Oh and @jonathanpike don't worry about the failures. We have known issues with the jruby 1.7 version and we are removing it very shortly. I'll just override the errors here and we can move forward. 😄

**Comment by ttwo32** [comment]
@ptrimble No problem.:+1:

**Comment by ptrimble** [comment]
@jonathanpike Erm...sorry, but I guess the other merge caused a small conflict. I'm betting it's a generated definition thing. Would you mind rebasing and pushing up the amended commit?

Sorry!

**Comment by jonathanpike** [comment]
@ptrimble Wow, Github made that super easy.  All I needed to do was click an "Update branch" button and it's ready to go.  Looks like you can merge away!

**Comment by ptrimble** [comment]
Whoa, really? Wow. I didn't know! Yeah, I'll merge. Thanks!

**Comment by jonathanpike** [comment]
Just a heads up -- I'll be pushing an update to these definitions (in a new PR) sometime next week.  I've been talking to the author of the [Ruby lunar date library](https://github.com/sunsidew/ruby_lunardate), which provides a programatic way of calculating the lunar holidays without gigantic case statements, and he's agreed to let Holidays use his code (much like the Julian calendar calculator).  It'll help with a lot of the Asian holidays that still rely on lunar dates!

**Comment by ptrimble** [comment]
Fantastic! That's great to hear, thanks for putting the effort into this. 👍 

A piece of info right back at you: we are planning on splitting the definitions out into a separate repository so that we can begin to use them for languages other than ruby. For example, I plan on writing a Go library sometime soon.

You can find the definitions here: https://github.com/holidays/definitions

Now, depending on how smoothly things go in the near future we might not have made the full switch yet so go ahead and put the definitions here (like normal) if I haven't moved yet. If I have moved then submit the YAML changes on the other repo and I'll handle generating the final ruby classes here. 

I'm still feeling out how this definition split is gonna go so if you have feedback please feel free to provide it. I'm not 100% sure how I'm gonna deal with logic like what you are referring to (that is currently written only in Ruby) so for the time being even if the definitions reside physically in another repo continue to do the same kinds of updates that we do today. Don't worry about making the logic somehow generic or anything. 😄

**Comment by ttwo32** [comment]
@jonathanpike Awesome!! Thanks for your help！!

**Pull request merged**
