### PR TITLE
Removed incorrect comments per issue #270

### PR DESCRIPTION
**Pull request by morrme**

### CODE REVIEW

**Comment by ppeble** [comment]
🤕 

@morrme I was wrong! There ARE tests that apparently are affected by this! They exist here: https://github.com/holidays/holidays/blob/master/test/holidays/definition/context/test_generator.rb

If you are still willing, you'll need to go and find if any lines have the text that you removed and remove it from the 'expected' text. For example, here is one of the lines: https://github.com/holidays/holidays/blob/master/test/holidays/definition/context/test_generator.rb#L161

You can verify it locally by running:

```sh
make setup
```

The above line will set everything up locally for running tests.  Then run:

```sh
make test
```

If it passes locally it should pass on travisci!

These tests are not well written so don't feel bad if they are confusing. These are last up on my quest to rewrite all of the tests in this project. 😄 

If you would prefer not to do it just let me know, I can finish it up. Thanks for submitting this!

**Comment by morrme** [comment]
@ppeble I was just digging up that test per the failure information. I'm on it!

**Comment by ppeble** [comment]
Great! Thank you! I'm awake and online if you need to discuss anything or have any questions. 

I'm on baby duty with my newborn and he is asleep right now so I'm basically sitting in the dark hoping he doesn't wake up. 😬

**Comment by morrme** [comment]
@ppeble Congrats on the newborn! 
Things look good here, so I'll be updating this PR and trying again 😀
holidays testing

**Comment by ppeble** [comment]
@morrme Thanks for contributing! I really appreciate it. If you ever want to talk about any of the issues that come up  or have other ideas on how to improve this project just hit me up. I'm always willing to discuss things. ❤️

**Comment by morrme** [comment]
@ppeble It was my pleasure! I am happy to support such a fun project. I hope I can help out again in the future. 

It seems like you're not alone with the multiple coveralls messages: 
https://github.com/lemurheavy/coveralls-public/issues/491

**Comment by ppeble** [comment]
Oooh, thank you. I'll add it to the issue we have tracking this. 👍

**Pull request merged**
