### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by ptrimble**
I am opening up this PR to solicit feedback on the current progress of the refactoring. I am aiming for a refactor of structure/style only. I am trying to only add to existing tests and would like as much backwards compatibility as possible. That means that all methods currently publicly available will remain unchanged.

That said, there are a few things that will change. I'll keep a list in this initial description and add to it as I continue:

* Remove automatic monkey-patching of `Date` class, use optional core extension instead
* Remove unnecessarily public methods from main `Holidays` module (with necessary changes to any definitions)
* Add region validation so unknown regions cannot be arbitrarily loaded. This required some definition cleanup in some cases since we had tests for what I presume were old regions that no longer exist.

Any/all feedback welcome! I'll continue to add commits as I move forward.

### CODE REVIEW

**Comment by ptrimble** [comment]
I don't think anyone is really monitoring this but I'll put it out anyway: this is turning into basically a complete rewrite. I am going to rename the branch. The only things that will remain the same:

1) Definition YAML format
2) *most* of the public API

I've reached this conclusion while trying to split out how definitions are merged. Since merged defs are stored in class vars in lib/holidays.rb I am unable to really split it out without drastically changing how things are stored in memory. My goal is that the code will change but hopefully most users won't notice a difference.

In addition, I am removing things that are unnecessarily public but leaving what I consider the 'main' methods ('on', 'between', etc). In fact, everything in lib/holidays.rb that is currently 'private' is actually 'public' because of a misunderstanding of how 'self' works. I'm cleaning that up as I go.

This will be a major version bump and I'm going to have to come up with some way to do some test releases of this. I am not concerning myself at all with performance initially so I imagine that will be the biggest loser here but I'm confident that I can address it quickly after we are stable.

**Comment by ptrimble** [comment]
My thinking right now is to merge and release a new breaking version change (v3.0.0). If you aren't semantically versioning when pulling this gem then...you'll need to go back and specify the older version. This is what breaking changes are for. :smile: 

If anyone objects to this and would prefer some kind of prerelease gem for testing then let me know.

I doubt anyone is reading these comments anyway but I thought I would ask.

**Comment by espen** [comment]
> I don't think anyone is really monitoring this

I am! Didn't have time to test this when you wrote the comment but using 3.1.0 in production now. I ended up skipping the date monkey patching all together and now using ```Holidays.on(date, :region).any?``` instead of ```date.holiday?(:region) ```. Thanks for the work and keeping the gem alive :)

**Comment by ptrimble** [comment]
Thank you for the kind words! I appreciate it. :smile:

**Pull request merged**
