### PR TITLE
Add year-range feature.

### PR DESCRIPTION
**Pull request by ttwo32**

### CODE REVIEW

**Comment by ptrimble** [comment]
@ttwo32 I think this looks good! Once you add a commit to address the test coverage decrease I'll go ahead and merge and then push out a minor version bump release.

Thanks again for this!

**Comment by ttwo32** [comment]
Thank you for reviewing code！！
I will add a test code soon, so please wait for a few days. :smile:

**Comment by ptrimble** [comment]
:+1: Sounds good!

**Comment by ttwo32** [comment]
@ptrimble Sorry to keep you waiting. I added test code and rewrite between.rb.
I was relieved that the test coverage upped.

Where should I write an explanation how to use year_range feature?(Readme.md??)

**Comment by ptrimble** [comment]
Fantastic! Let's get this bad boy merged and I'll get a release out. :+1:

**Comment by ttwo32** [comment]
@ptrimble Thanks!! Congrats version up, and a release out :tada:

**Pull request merged**
