### PR TITLE
Add type informal to 'Dodenherdenking' [dutch]

### LINKED ISSUE #116: How to override holidays
We're using the holidays gem to prevent performing actions on holidays, but some holidays defined in the yaml files, such as liberation day, is an normal working day.

I know how to add custom holidays, but how can i override a specific holiday?

### PR DESCRIPTION
**Pull request by MathijsK93**
Dodenherdenking is in the netherlands not an official holiday.

More info (dutch):
http://www.rijksoverheid.nl/onderwerpen/schoolvakanties/vraag-en-antwoord/wanneer-zijn-de-officiele-feestdagen-in-nederland.html

Fixes #116

### CODE REVIEW

**Comment by ptrimble** [comment]
Sorry! I gotta fix some stuff on travis and coveralls and then I'll get to this.

**Comment by ptrimble** [comment]
This looks good. I'll just get coveralls fixed and merge.

**Comment by ptrimble** [comment]
Actually, I am just going to merge this. The coveralls thing is unrelated. Thanks for the fix!

**Comment by MathijsK93** [comment]
Thanks @ptrimble when will the version be bumped?

**Comment by ptrimble** [comment]
I'll do it this morning. I meant to do it last night after I got off of the train for my commute but...I forgot. :fearful:

**Comment by MathijsK93** [comment]
:+1:

**Comment by ptrimble** [comment]
Done! Let me know if you run into any issues.

**Pull request merged**
