### PR TITLE
melbourne cup is now a state-wide holiday

### PR DESCRIPTION
**Pull request by ghiculescu**
i haven't really used git submodules before so hopefully i haven't totally screwed this up!

### CODE REVIEW

**Comment by ghiculescu** [comment]
okay i definitely screwed that up.

**Comment by ghiculescu** [comment]
@ptrimble are you able to merge https://github.com/holidays/definitions/pull/8 and then advise on what i should do here?

**Comment by ptrimble** [comment]
@ghiculescu Hey, sorry for the delay. So the plan for the new 'definitions' repo is that you check in your definitions over there and I then we (the maintainers of this gem) handle generating stuff and checking in whatever we need. The idea is that we will just have users make definition changes and, as long as it passes our internal validation, any repos like this can update on their own time.

So the pattern would be:

1) User changes `holidays/definitions`. That gets accepted and merged.
2) Maintainer (or user, doesn't matter, but in the beginning it can just be maintainer) will update the submodule in this repo to point to `master` on the definitions, which has the newest stuff.
3) Generate the new ruby classes with the new definitions
4) Create a PR and merge for a release

I don't know how this will play out, honestly. The main reason I wanted to do this is that I want to write repositories in other languages (like Go or Swift) and in order to do that we needed to split out the definitions from the Ruby repo. But I don't know if this will work in the long term, to be entirely honest, so feedback is welcome. We don't have to stick to this setup. I'm not married to it.

We tried to update the [CONTRIBUTING.md](https://github.com/holidays/holidays/blob/master/CONTRIBUTING.md) doc to outline this process but it's entirely possible that it is not clear on how to proceed. Like I said, feel free to open issues/PRs if you feel that any part of it is confusing or weird.

**Comment by ghiculescu** [comment]
Hey @ptrimble thanks for the explanation! The main issue with that workflow for me is that at the moment we target a github URL in our application's `Gemfile`. We do this so that we can immediately see public holiday changes rather than waiting for a new version of the gem to roll out. So we don't really care if a PR gets merged, we just do it because it's the right thing to do!

At the moment our `Gemfile` looks like this:

```
gem 'holidays', git: 'https://github.com/tandahq/holidays.git', ref: "3d01d68"
```

So as far as I can see that means we would need to update our fork of `holidays/definitions`, then also update our fork of `holidays/holidays`, then update the ref in our Gemfile. But we would only ever do a PR of `holidays/definitions`, and we would need to occasionally keep our fork of `holidays/holidays` in sync with its upstream.

Does that workflow sound right to you?

(One relatively ambitious solution to these problems would be if `holidays/holidays` didn't include the `generated_definitions` folder, but instead generated these definitions at runtime in some way. If that worked, could also have it always load the latest definitions from Github at app load time if you wanted to.)

**Comment by ptrimble** [comment]
@ghiculescu I'm really sorry, I did read this but simply let it fall through the cracks. :face_with_head_bandage: 

Yes, I think your workflow makes sense. I'm....very intrigued by the 'generate at runtime' approach. I wonder how much slower it really is to do it that way. Meaning that I wonder if reading a single YAML file and generating something to load into memory is _actually_ slow. I wonder if the 'slow' part is writing the files to disk.

I think that unless we do it at runtime my new setup is going to be worse for you. I definitely didn't think about your workflow when splitting out to the submodule. Let me think about this. I wonder if there is a cleaner, better way to do this. 

For example, maybe instead of using submodules I actually physically copy the defs into `holidays` and provide `make` targets that make it easy to pull from branches. That way you can tell the make target which branch (master being a valid branch) to copy down. That eliminates the need for submodules, which are inherently crazy.

I'm not sure. Let me think a bit. For the time being I think your own option is what you laid out. :frowning_face:

**Comment by ghiculescu** [comment]
Yeah, especially now that holidays lazy loads, you would only need to generate definitions from a particular YAML file when it's first requested. Given how the rake task to generate *all* the definitions is quite fast, I imagine just generating one would be very fast!  But if you were really worried about performance, you could just do this in an initializer.

**Pull request closed without merging**
