### PR TITLE
Large refactor of custom methods to address issue 144

### PR DESCRIPTION
**Pull request by ptrimble**
This is a largish refactor to consolidate and normalize how 'custom methods' are handled by the gem. The issue is that we relied on requiring files when regions were loaded, which loaded region-specific methods into the `Holidays` namespace. This was...bad, in a lot of ways. It caused conflicts and it also meant that it was very hard to handle the loading of the 'on the fly' custom methods, which was brought out here: https://github.com/holidays/holidays/issues/144

There are a lot of big changes here. Every single definition needed to change slightly and I changed how functions are named and organized in each definition file. While there are a lot of file changes hopefully they are clear.

Opening this up to feedback. I'm continuing to test issue 144 and might add more work if it is not fully addressed by this PR.

### CODE REVIEW

**Comment by ptrimble** [comment]
Also, note to self: I must update the `definitions/README.md` to match the new 'custom method' targets.

**Comment by ptrimble** [comment]
Also, note to self: must merge outstanding PRs before merging this one. I should handle merge conflicts here, not force other contributors to handle my conflicts.

**Comment by ptrimble** [comment]
Alright, this is ready for final testing/review. I have put together an example of how I tested in a gist here: https://gist.github.com/ptrimble/463485b5e6b8ac7ee112079c0c137147

I will investigate the failing jruby piece now.

**Comment by ptrimble** [comment]
Jruby fixed. As you can see from the commit the `Module.const_get("Holidays::#{region_name}")` line was causing it. I guess jruby 1.7 doesn't like the colons. Chaining the `const_get()` calls works fine in all rubies, though.

All done! I'm moving on to the other PRs while this is looked at by anyone who is interested. :smile:

**Comment by md5** [comment]
@ptrimble I've tested the changes briefly and they work fine for me. Our use case is pretty simple, so I can't claim to have tested much beyond there.

**Comment by ptrimble** [comment]
Thank you @md5! Some testing is always preferrable to none. I'm hitting it from a bunch of different angles and I think I'm in the clear. If @ttwo32 has no code change suggestions I will finish with the other PRs, deal with conflicts, and get this out.

I think I will do a release on the older 3.X.X release just so people can get the latest defs without needing to worry about breaking changes and bump it to 4.0.0 with this PR. Most people won't notice a change but better to be clear and safe.

Thanks again!

**Comment by ptrimble** [comment]
Another quick note: I've done simple benchmarking going off of this gist I put together to organize my thoughts, located [here](https://gist.github.com/ptrimble/cc6195e815acfa559bda).

There is a performance hit but we're still talking around a 0.1 seconds to require the `holidays` gem. I think this is an acceptable tradeoff.

**Comment by Eric-Guo** [comment]
It's really a big refactor! :joy:

**Comment by ptrimble** [comment]
Oh yes! It turned out to be very, very large. Much larger than I intended! But I saw the chance to rework something that was on my radar for a long time and I took it.

The `require` of the generated definitions when you looked up a region caused very weird bugs that were hard to troubleshoot. Now that the definitions are loaded in-memory and not simply loaded into the `Holidays` namespace via `require` I have been able to fix bugs much, much faster.

Hopefully my prediction that this will be better in the long term will turn out to be correct! Only time will tell. 😄

**Comment by ttwo32** [comment]
@ptrimble  Good work！！ 👍 
Thank for your hard work.

**Pull request merged**
