### PR TITLE
Add methods to calculate lunar dates

### PR DESCRIPTION
**Pull request by jonathanpike**
Further to my [previous comment](https://github.com/holidays/holidays/pull/227#issuecomment-249375231) upon submitting definitions for the Republic of Korea, I've asked the author of the [ruby_lunardate](https://github.com/sunsidew/ruby_lunardate) library and he's agreed to letting the holidays gem use his library.  

I've done the work of adding the library into holidays here.  I'm also submitting a PR to the definitions repo to update the definitions for the Republic of Korea to use these new methods.

### CODE REVIEW

**Comment by ghiculescu** [comment]
hey @jonathanpike - i'm not really familiar with lunar/solar calendars. I was just wondering if this PR would make it simple to calculate Vietnam's [Hung Kings Commemorations](https://en.wikipedia.org/wiki/Public_holidays_in_Vietnam) ("10th day of the 3rd lunar month") or if that's not really the same thing?

**Comment by jonathanpike** [comment]
@ghiculescu lunar calendars are really interesting!  Yes, this PR would make it simple to calculate lunar holidays.  You would put Hung Kings Commemoration in the definition file like this: 

```
3:
- name: Hung Kings Commemorations
   regions: [vi]
   function: lunar_to_solar(year, month, day)
   mday: 10
```

The lunar_to_solar method would convert the 3rd month and 10th day to the correct solar date for whatever year is being requested.  

One caveat: Because Vietnam (Hanoi) is GMT+0700 and the Republic of Korea (Seoul) is GMT+0900, there could be slight discrepancies (off by 1 errors) in some years.  This PR was mainly done for Korean holidays, although I'm sure adjustments can be made to make it even more general.  For an explanation of why this is, this Quora Q and A is pretty good: https://www.quora.com/Is-the-Lunar-New-Year-celebrated-by-Koreans-on-the-same-date-as-the-Chinese-Lunar-New-Year

**Comment by ghiculescu** [comment]
"This last occurred in 2009, and will occur again in 2033." haha, great.

Thanks for that!

**Comment by jonathanpike** [comment]
Absolutely.  Are there any other lunar holidays that should be added?

**Comment by ghiculescu** [comment]
Not that I know of. I was just updating Vietnamese holidays in https://github.com/holidays/definitions/pull/27 and noticed it there.

**Comment by ppeble** [comment]
Great PR, sorry for the delay. I'm ignoring the coverage decrease. 0.02 is nothing, who knows why it freaked out. Thank you!

**Pull request merged**
