### PR TITLE
Added Dutch version of Belgian Holidays

### PR DESCRIPTION
**Pull request by mykey**
Belgium is a trilingual country. 60% of the population speaks Dutch. I think that warrants a Dutch version of the original French file.

### CODE REVIEW

**Comment by ptrimble** [comment]
Hello @mykey, thanks for the PR! I think this is a very reasonable idea. I will look into this PR this weekend. 

I have concerns over how this will work in practice with the existing holidays. Will each day return two identical holiday entries (identical except for the language of the name)? Let me play with it today.

**Comment by ptrimble** [comment]
Actually, slight amendment: I think it would be clearer for the user to be forced to specify exactly which sub-region they wanted. So it would either be `:be_vlg` or `:be_wal`. Passing in just `:be` would result in a 'not found' error.

**Comment by mykey** [comment]
Hey Ptrimble, sorry for the long wait. Thanks for your input.

Flanders is mostly dutch speaking, but there are a little of French speaking people living in it too, mostly near Brussels and the language border.
Wallonia is French speaking, with a German speaking minority in the east and a little Dutch speaking people, mostly living in the vicinity the language border.

Since language rather than region is the determining factor here, wouldn't it be best to have people choose a language instead of a region e.g. `:be_nl` and `:be_fr` instead of `:be_vlg` or `:be_wal`? Or am I missing something? 
Region is also rather complicated in Belgium, so it's something I'd steer away from. Without getting into the details of it, depending on the subject matter there are certain overlaps, as is displayed here: [image](http://www.belgium.be/en/about_belgium/government/federale_staat/map)

Someone might want to make a `:be_de` (German) version in the future? I think this way of working  could work for China as well e.g. Mandarin, Cantonese,... where it's also not that obvious how to define regions instead of languages: [image](http://www.chinalanguage.com/images/lingmap.png)

**Comment by ptrimble** [comment]
Yes, I like this! I would like to go in this direction. Honestly the region names I inherited don't always strictly follow the ISO standard anyway so this isn't even a deviation.

I'll work something up this weekend and hopefully we can put this to bed. Thanks for the feedback!

**Comment by ptrimble** [comment]
I *finally* finished my other work on this gem and so now I am going back to process these PRs. I have made the changes we discussed, created a branch under my own account (attributing the commits to you), and opened the alternate PR here: https://github.com/holidays/holidays/pull/180

I am closing this for the other one. I'll merge as soon as the builds pass. Thanks for your patience and thanks for talking this over!

**Pull request closed without merging**
