### PR TITLE
Add more JRuby version in Travis matrix

### PR DESCRIPTION
**Pull request by guizmaii**
Hey,

I messed up in my merges for the initial PR here: https://github.com/holidays/holidays/pull/316 so I recreated one here. Sorry. :/

### CODE REVIEW

**Comment by ppeble** [comment]
As with the other PR, I am on board with adding more jruby to the test matrix but I'm worried about the drop in coverage. Do you know why it is failing?

**Comment by ppeble** [comment]
Pinging one more time to see if we can figure out why the jruby test is failing in the newer version.

**Comment by guizmaii** [comment]
hey @ppeble,

I'm sorry. I don't know why the tests with JRuby give an other coverage result.

**Comment by ppeble** [comment]
@guitarman Relaunched! 

And no worries! I will spend an hour or two researching as well. If it is just not obvious to me in that timeframe then I'll close out this PR for the time being until I have some more time to devote to jruby.

**Comment by ppeble** [comment]
Okay, I am going to close this PR and add the newer jruby versions you requested into my [v8.0.0 PR](https://github.com/holidays/holidays/pull/339). I did a bunch of testing and while I still don't fully understand why jruby behaves the way it does with coverage I think I've reached a solution of sorts.

I would also like to drop the older jrubies that match up with ruby 2.2 and 2.3. In that other PR I am proposing we drop them since 2.2 has already ended support and 2.3 is ending support in April this year.

Thanks for suggesting this and giving me the push I needed to finally address the jruby bits!

**Pull request closed without merging**
