### PR TITLE
Update definitions.

### PR DESCRIPTION
**Pull request by ttwo32**
Update defifnitions.

See details:
https://github.com/holidays/definitions/pull/140
https://github.com/holidays/definitions/pull/141
https://github.com/holidays/definitions/pull/142

### CODE REVIEW

**Comment by ttwo32** [comment]
@ppeble Hi @ppeble :)
I created this PR.
Please review my PR at your free time.
Thanks.:)

**Comment by ALandscheidt** [comment]
It would be nice if we could merge this PR 🙂

**Comment by mwannewitz** [comment]
Is there any update on this? @ppeble

**Comment by ppeble** [comment]
I apologize for letting this sit. I'll merge this in and get the `v5.0.0` release out as I should have done previously.

**Comment by ttwo32** [comment]
Thank you @ppeble . :)

**Comment by ppeble** [comment]
Once again I apologize for letting this sit for so long. I just pushed [v8.0.0 on Rubygems](https://rubygems.org/gems/holidays/versions/8.0.0). It includes all of the latest definitions in the [definitions repo](https://github.com/holidays/definitions) and is a breaking change only because we are dropping ruby support for old, unsupported rubies.

Thanks for your patience!

**Pull request merged**
